### ISSUE TITLE
Cannot read property 'offsetHeight' of undefined

### ISSUE THREAD

**Issue by sam2x** [Coraza/angular-emoji-popup#10]
Hey, everytime i run the webpage with the emoji code i got the following error : 

    TypeError: Cannot read property 'offsetHeight' of undefined
       at emojiDirectives.js:145
       at angular.js:16380
       at completeOutstandingRequest (angular.js:4940)
       at angular.js:5328

Tracking the line code, the error is from : 
            
         var height = richTextarea.offsetHeight;

So _richTextarea_ is undefined. I don't get why... He should be instanciated by the following line 30 of emojiDirectives.js :

             richTextarea = $(
                    '.emoji-wysiwyg-editor', element)[0];

_.emoji-wysiwyg-editor_ is supposed to be added by _jquery.emojiarea.js_ on line 339 : 

		this.$editor = $('<div>').addClass('emoji-wysiwyg-editor');

Has anyone got this error ? Any pointers would be appreciated.

**Comment by sam2x** [comment]
Ok, nevermind, i solved it. i marked "emoji-form emoji-message" inside a tag who already has a personal directive, seems it skiped the code triggered by this marker. 
Just another question : is that possible to use it with a "input" widget and not a textarea ?

**Comment by madhur** [comment]
:+1:  Right now its only possible with `contenteditable`

**Comment by karthik-rp** [comment]
@sam2x 
How did you resolve this problem?
Even I'm using is inside a tag which is part of another directive. The way I've modeled it requires it to be a part of directive's template.
