### ISSUE TITLE
Styles of Demo Page are minified into 

### ISSUE THREAD

**Issue by 3x14159265** [Coraza/angular-emoji-popup#15]
the minified version (dist/emoji.min.css) also contains the styles from the demo page (css/styles.css). Therefore, elements like body background and h1 are altered. Please remove this from the minified version.

**Comment by luccascorrea** [comment]
+ 1

**Comment by luccascorrea** [comment]
+1

**Comment by madhur** [comment]
Resolved with 1.1.0

https://github.com/Coraza/angular-emoji-popup/releases/tag/1.1.0
