### ISSUE TITLE
Submit is not catching emojiMessage.messagetext

### ISSUE THREAD

**Issue by jrmatos** [Coraza/angular-emoji-popup#17]
I've changed the behavior of the textarea to look like a input text (submit when `enter` is pressed), but I can not read the property `$scope.emojiMessage.messagetext` when I catch the submit. I'm doing a chat and it's important because everyone likes to send messages just pressing enter.

**Comment by jrmatos** [comment]
The $scope.emojiMessage.messagetext is updating just when the textarea lose focus

**Comment by tokkerbaz** [comment]
how did you solved that problem can you tell??

**Comment by jrmatos** [comment]
I managed to solve this but I didn't remember how. It has more than one year. Can you tell what's happening in your case?

**Comment by tokkerbaz** [comment]
when i put emojis to textarea it dont read, it shows as `img `in `div`, but i cant save it to database, and i cant convert it to `unicode`

**Comment by tokkerbaz** [comment]
I mean, input emojis are working well, but output decoded message/encoded message/ evenif smileys are not showing, in demo all working fine...
