### ISSUE TITLE
Not working with ionic framework

### ISSUE THREAD

**Issue by mchirino89** [Coraza/angular-emoji-popup#21]
Hi there. I'm having some issues integrating this lib with an ionic project, it doesn't show any error on console but emojis only work well until second click. After click by the third time, they start appending right after the first emoji and text cursor won't work properly after that. Please help.

<img width="288" alt="captura de pantalla 2015-09-19 a las 2 23 17 p m" src="https://cloud.githubusercontent.com/assets/1657723/9977691/fde872be-5ed9-11e5-838c-2f42694b6ff7.png">

**Comment by akashdeepshah** [comment]
same problem here.

**Comment by madhur** [comment]
Can you elaborate on the problem?

I have added a demo page working with ionic:

https://github.com/Coraza/angular-emoji-popup/blob/master/dist/demo.html

**Comment by sagardalal21** [comment]
I'm also facing same problem....
icons not going to be display in textbox..
Any one have solution..??

**Comment by madhur** [comment]
@sagardalal21 Did you check out the demo

https://github.com/Coraza/angular-emoji-popup/blob/master/dist/ionic.html

**Comment by sagardalal21** [comment]
yes..i have checked..
but i shows me an error likewise:
' Cannot read property 'offsetHeight' of undefined '

**Comment by ramthakur1991** [comment]
Hi there. I'm having some issues integrating this lib with an ionic project, it doesn't show any error on console but emojis only work well until second click. After click by the third time, they start appending right after the first emoji and text cursor won't work properly after that. Please help. I'm facing this issue did any here we get the solutions .

**Comment by madhur** [comment]
Will it be possible to share your project with me @ramthakur1991

**Comment by ramthakur1991** [comment]
yeah sure

**Comment by ramthakur1991** [comment]
Here's the link of the code which is a Ionic project
https://github.com/ramthakur1991/emoticons

**Comment by mchirino89** [comment]
I face the same issue than @ramthakur1991, let me know if there's a way around it please.

**Comment by mukul7052** [comment]
I am also facing the same issue than @ramthakur1991, let me know if you find any solution regarding this.It works fine in web but give issue with device.

**Comment by siddharth2824** [comment]
Hello Madhur. I was trying your demo and its working fine on browser but when i try to implement it in my application  i faced the same problem as mentioned above by @ramthakur1991  and @mchirino89 ...Please let me know once you done with your updation.Thanks

**Comment by madhur** [comment]
Sure, Will revert in couple of days.

**Comment by siddharth2824** [comment]
Okay , Thanks for your reply but in the mean time can you provide me commit number when this thing was working and stable for devices too.

**Comment by dotnetexpert** [comment]
hi, i am also facing the issue
i am working on a ionic project. i used these emoji there. when the app runs on mobile browser , emoji works well , but when it runs on desktop browser, emoji doesn't work. it opens the popup but doesn't gets selected. kindly help me . i am breaking my head for many days.
