### ISSUE TITLE
How to change shortcuts (like ":D" instead of ":smile:")?

### ISSUE THREAD

**Issue by Ahmed-Emad** [Coraza/angular-emoji-popup#27]

**Comment by iamsaksham** [comment]
I've fixed this issue and created a new filter for it namely "emoticonToSmiley". I've created a pull request for it, till then you can check it out at my github  with repository name "emoji"

**Comment by madhur** [comment]
Cool, Thanks. Will check it out

**Comment by Ahmed-Emad** [comment]
Perfect, Thanks man.
