### ISSUE TITLE
insert char delete previous emoji

### ISSUE THREAD

**Issue by angeliqueIcono** [Coraza/angular-emoji-popup#3]
Hi, 
I have an issue with your plugin. When I insert an emoji and then start writting characters, my emoji are removed from my ng-model. I am searching for a solution since yesterday but I don't know where this can happened in the code.
Can you help me please?

**Comment by madhur** [comment]
Can you post the code?

On Thursday, February 26, 2015, angeliqueIcono <notifications@github.com>
wrote:

> Hi,
> I have an issue with your plugin. When I insert an emoji and then start
> writting characters, my emoji are removed from my ng-model. I am searching
> for a solution since yesterday but I don't know where this can happened in
> the code.
> Can you help me please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Coraza/angular-emoji-popup/issues/3>.
>


-- 
--
Madhur
+91 9999 55 9848

-- 
CIN No. U72900CH2009PTC031912
