### ISSUE TITLE
pls compile the recent fix

### ISSUE THREAD

**Issue by sheyooo** [Coraza/angular-emoji-popup#30]
please compile and the emoji.min.js with fix provided by @k-zakhariy  as soon as possible

**Comment by madhur** [comment]
Can you do it and provide me with a pull request? @sheyooo

**Comment by sheyooo** [comment]
will try :-)

**Comment by madhur** [comment]
Thanks let me know if you face any issues

**Comment by sheyooo** [comment]
Done pls review and merge

**Comment by sheyooo** [comment]
I have sent the pull request @madhur pls its urgent review the changes and merge

**Comment by madhur** [comment]
check my comment
