### ISSUE TITLE
Dont show popup any more 

### ISSUE THREAD

**Issue by luciano-work** [Coraza/angular-emoji-popup#39]
I use for a long time this project, but today doesn't work the popup.

![imagem 2](https://cloud.githubusercontent.com/assets/12519008/15027185/d0ddc77c-1218-11e6-9368-cc377fb9e1e2.png)

You can see the demo page: http://coraza.github.io/angular-emoji-popup/ doesn't work also.

How to fix it?

**Comment by madhur** [comment]
Are you still having the issue?

**Comment by luciano-work** [comment]
I change for this project: https://github.com/one-signal/emoji-picker

**Comment by madhur** [comment]
Thanks for letting me know. The https://github.com/one-signal/emoji-picker is better. I'll probably deprecate this library and redirect users to that one.
