### ISSUE TITLE
Pop-Up not displaying

### ISSUE THREAD

**Issue by sumitkumar1209** [Coraza/angular-emoji-popup#6]
The content of css file src/emoji.css are not present in dist/emoji.min.css and hence no popup is displayed in the webpage.

It took me a while to implement this in my project, so I am just adding it here to save time for others. Use CSS  from src folder or add the content of src/emoji,css in your main stylesheet.

**Comment by madhur** [comment]
Hey. Thanks. Can you send me a pull request.

**Comment by sumitkumar1209** [comment]
yeah sent one request

**Comment by madhur** [comment]
:+1:
